### ISSUE TITLE
Lambda Docs: Spelling error

### ISSUE THREAD

**Issue by markwdalton** [LambdaLabs/lambda-docs#165]
https://docs.lambdalabs.com/linux/prevent-system-from-sleeping/
Spelling error in 'hibernate' vs current shows 'hybernate':

It should be:
sudo systemctl mask hibernate.target hybrid-sleep.target \
  suspend-then-hibernate.target sleep.target suspend.target

On Ubuntu 20.04 and 22.04:
$ find /lib/systemd -name '*sleep*.target' -o -name '*hibernate*.target' -o -name '*suspend*.target'
/lib/systemd/system/suspend.target
/lib/systemd/system/hybrid-sleep.target
/lib/systemd/system/sleep.target
/lib/systemd/system/suspend-then-hibernate.target
/lib/systemd/system/hibernate.target

**Comment by cbrownstein-lambda** [comment]
@markwdalton Thanks for catching this! I fixed it in https://github.com/LambdaLabs/lambda-docs/commit/dadb6c30d94df575cedd99c35dc3c58d37ae9ddf.
